In [1]:
import pandas as pd

inventory = pd.DataFrame({
    'ingredient': [
        'Chicken',
        'Rice',
        'Tomato',
        'Eggs',
        'Yogurt'
    ]
})

inventory

  ingredient
0    Chicken
1       Rice
2     Tomato
3       Eggs
4     Yogurt

In [2]:
recipes = pd.DataFrame({
    'recipe_name': [
        'Chicken Rice Bowl',
        'Tomato Omelette',
        'Yogurt Salad'
    ],
    'ingredients': [
        ['Chicken', 'Rice'],
        ['Tomato', 'Eggs'],
        ['Yogurt', 'Tomato']
    ],
    'calories': [
        520,
        280,
        180
    ],
    'protein': [
        42,
        18,
        8
    ]
})

recipes

         recipe_name       ingredients  calories  protein
0  Chicken Rice Bowl   [Chicken, Rice]       520       42
1    Tomato Omelette    [Tomato, Eggs]       280       18
2       Yogurt Salad  [Yogurt, Tomato]       180        8

In [3]:
available = set(inventory['ingredient'])

recommended = []

for _, row in recipes.iterrows():
    recipe_ingredients = set(row['ingredients'])

    if recipe_ingredients.issubset(available):
        recommended.append(row)

recommended_df = pd.DataFrame(recommended)

recommended_df

         recipe_name       ingredients  calories  protein
0  Chicken Rice Bowl   [Chicken, Rice]       520       42
1    Tomato Omelette    [Tomato, Eggs]       280       18
2       Yogurt Salad  [Yogurt, Tomato]       180        8

In [4]:
for _, recipe in recommended_df.iterrows():

    print("=" * 40)

    print(f"🍽 Recipe: {recipe['recipe_name']}")
    print(f"🔥 Calories: {recipe['calories']}")
    print(f"💪 Protein: {recipe['protein']} g")

========================================
🍽 Recipe: Chicken Rice Bowl
🔥 Calories: 520
💪 Protein: 42 g
========================================
🍽 Recipe: Tomato Omelette
🔥 Calories: 280
💪 Protein: 18 g
========================================
🍽 Recipe: Yogurt Salad
🔥 Calories: 180
💪 Protein: 8 g

In [5]:
available = set(inventory['ingredient'])

recommended = []

for _, row in recipes.iterrows():
    recipe_ingredients = set(row['ingredients'])

    if recipe_ingredients.issubset(available):
        recommended.append(row)

recommended_df = pd.DataFrame(recommended)

recommended_df

         recipe_name       ingredients  calories  protein
0  Chicken Rice Bowl   [Chicken, Rice]       520       42
1    Tomato Omelette    [Tomato, Eggs]       280       18
2       Yogurt Salad  [Yogurt, Tomato]       180        8

In [6]:
goal = input(
    "What is your goal? (Weight Loss / Weight Gain / Muscle Gain): "
)

StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

In [ ]:
recipes.columns

In [ ]:
print(recipes.columns)
print()
print(recommended_df.columns)

In [ ]:
if goal == "Weight Loss":
    recommended_df = recommended_df.sort_values(
        by="calories"
    )

elif goal == "Weight Gain":
    recommended_df = recommended_df.sort_values(
        by="calories",
        ascending=False
    )

elif goal == "Muscle Gain":
    recommended_df = recommended_df.sort_values(
        by="protein",
        ascending=False
    )

recommended_df.head(10)

In [ ]:
print("🍽 SmartPantry Recommendation")
print()

for _, recipe in recommended_df.head(10).iterrows():

    print(f"🍲 {recipe['recipe_name']}")
    print(f"🔥 Calories: {recipe['calories']}")
    print(f"💪 Protein: {recipe['protein']} g")
    print("-" * 40)

In [ ]:
inventory_expiry = pd.DataFrame({
    'ingredient': [
        'Chicken',
        'Tomato',
        'Yogurt',
        'Rice'
    ],

    'days_left': [
        2,
        4,
        1,
        60
    ]
})

inventory_expiry

In [ ]:
print("⚠️ Expiry Alert")
print()

for _, item in inventory_expiry.iterrows():

    if item['days_left'] <= 3:

        print(
            f"{item['ingredient']} should be used within "
            f"{item['days_left']} day(s)"
        )

In [ ]:
critical_items = len(
    inventory_expiry[
        inventory_expiry['days_left'] <= 3
    ]
)

total_items = len(inventory_expiry)

waste_score = (
    (total_items - critical_items)
    / total_items
) * 100

print(
    f"♻️ Food Waste Prevention Score: "
    f"{waste_score:.0f}/100"
)

In [ ]:
user_profile = {
    "name": "Shahram",
    "goal": "Weight Loss",
    "daily_calorie_target": 1800
}

In [ ]:
def nutrition_coach(goal_recipes, user_profile):

    total_calories = goal_recipes['calories'].sum()
    total_protein = goal_recipes['protein'].sum()

    print("🌿 SmartPantry Nutrition Coach")
    print()

    print(f"Hello {user_profile['name']}")
    print(f"Goal: {user_profile['goal']}")
    print(f"Calories: {total_calories}")
    print(f"Protein: {total_protein} g")

    if total_calories < user_profile['daily_calorie_target']:
        print("✅ Below calorie target")
    else:
        print("⚠️ Above calorie target")

In [ ]:
if goal == "Weight Loss":
    result_df = recommended_df.sort_values(
        by="calories"
    )

elif goal == "Weight Gain":
    result_df = recommended_df.sort_values(
        by="calories",
        ascending=False
    )

elif goal == "Muscle Gain":
    result_df = recommended_df.sort_values(
        by="protein",
        ascending=False
    )

print("🍽 SmartPantry Recommendation")
print()

for _, recipe in result_df.head(10).iterrows():

    print(f"🍲 {recipe['recipe_name']}")
    print(f"🔥 Calories: {recipe['calories']}")
    print(f"💪 Protein: {recipe['protein']} g")
    print("-" * 40)

# SmartPantry Architecture

## 1. Inventory Management

## 2. Recipe Recommendation Engine

## 3. Nutrition Coach

## 4. Food Waste Prevention

## 5. Smart Shopping Prediction

In [ ]:
def nutrition_coach(goal_recipes, user_profile):

    total_calories = goal_recipes['calories'].sum()
    total_protein = goal_recipes['protein'].sum()

    print("🌿 SmartPantry Nutrition Coach")
    print()

    print(f"Hello {user_profile['name']}")
    print(f"🎯 Goal: {user_profile['goal']}")
    print(f"🔥 Calories: {total_calories}")
    print(f"💪 Protein: {total_protein} g")

    if total_calories < user_profile['daily_calorie_target']:
        print("✅ Below calorie target")
    else:
        print("⚠️ Above calorie target")

In [ ]:
nutrition_coach(recommended_df, user_profile)

In [ ]:
print("result_df exists:", 'result_df' in globals())
print("recommended_df exists:", 'recommended_df' in globals())

In [ ]:
import pandas as pd

## 5. Smart Shopping Prediction

In [ ]:
inventory_stock = pd.DataFrame({
    'ingredient': [
        'Eggs',
        'Milk',
        'Rice',
        'Chicken',
        'Tomato'
    ],

    'quantity': [
        2,
        1,
        10,
        1,
        3
    ]
})

inventory_stock

In [ ]:
def shopping_prediction(inventory_stock):

    print("🛒 Smart Shopping Assistant")
    print()

    low_stock = inventory_stock[
        inventory_stock['quantity'] <= 2
    ]

    for _, item in low_stock.iterrows():

        print(
            f"Add {item['ingredient']} "
            f"to your shopping list"
        )

In [ ]:
shopping_prediction(inventory_stock)

In [ ]:
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [ ]:
import pandas as pd

recipes_real = pd.read_csv(
    "/kaggle/input/datasets/shuyangli94/food-com-recipes-and-user-interactions/RAW_recipes.csv"
)

print(recipes_real.shape)
recipes_real.head()

In [ ]:
recipes_real.columns

In [ ]:
recipes_real[['name', 'ingredients']].head()

In [ ]:
available_ingredients = [
    "ground beef",
    "yellow onions",
    "diced tomatoes"
]

matches = recipes_real[
    recipes_real["ingredients"].apply(
        lambda x: all(item in x for item in available_ingredients)
    )
]

matches[["name","ingredients"]].head(10)

In [ ]:
matches[
    [
        'name',
        'minutes',
        'n_steps',
        'ingredients',
        'steps'
    ]
].head(3)

In [ ]:
matches = matches.copy()

matches["score"] = 1000 - matches["minutes"]

matches = matches.sort_values(
    by="score",
    ascending=False
)

matches[
    ["name", "minutes", "n_steps"]
].head(5)

In [ ]:
user_profile = {
    "goal": "Weight Loss",
    "preferred_time": 60
}

In [ ]:
matches["time_score"] = (
    user_profile["preferred_time"]
    - abs(matches["minutes"] - user_profile["preferred_time"])
)

matches = matches.sort_values(
    by="time_score",
    ascending=False
)

matches[
    ["name", "minutes", "time_score"]
].head(10)

In [ ]:
recipes_real["nutrition"].head()

In [ ]:
sample = recipes_real.iloc[0]

print("Recipe:", sample["name"])
print("Nutrition:", sample["nutrition"])

In [ ]:
len(recipes_real.iloc[0]["nutrition"])

In [ ]:
for i, value in enumerate(recipes_real.iloc[0]["nutrition"]):
    print(i, value)